"use client";
import { Providers } from "@/redux/provider";
import "./globals.css";

import { PersistGate } from "redux-persist/integration/react";
import { persistor } from "@/redux/store";
import ToastProvider from "@/components/toast.provider";
import GoogleAnalytics from "@/components/GoogleAnalytics";
import { Analytics } from "@/components/Ga";
import { Suspense } from "react";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// console.log(`${process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID}`);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <GoogleAnalytics
        GA_MEASUREMENT_ID={`${process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID}`}
      />

      <body>
        <ToastProvider>
          {" "}
          <Providers>
            {" "}
            <PersistGate loading={null} persistor={persistor}>
              {children}
            </PersistGate>
          </Providers>
        </ToastProvider>
      </body>
    </html>
  );
}
